name: full check suite
on:
  push:

env:
  REPORT_PATH: 'ci/cuke-report.json'
  CUCUMBER_SPLIT_CONFIGURATION_PATH: 'ci/cucumber-split-config.json'
  CLIENT: 'dc'

jobs:
  view_linter:
    runs-on: ubuntu-runner
    steps:
      - name: Install Git, Ruby, and dependencies
        run: |
          sudo apt update
          sudo apt install -y git ruby-full build-essential libyaml-dev shared-mime-info nodejs

      - name: Create /opt/hostedtoolcache directory and set permissions
        run: |
          sudo mkdir -p /opt/hostedtoolcache
          sudo chown runner /opt/hostedtoolcache && sudo chmod u+rw /opt/hostedtoolcache

      - name: Set up Ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true
          rubygems: 3.3.26
          working-directory: /home/runner/_work/enroll/enroll

      - name: Set PATH to include Ruby bin directory
        run: export PATH="/opt/hostedtoolcache/Ruby/2.6.3/x64/bin/:$PATH"

      - uses: actions/checkout@v3

      - name: Set FREEDESKTOP_MIME_TYPES_PATH
        run: export FREEDESKTOP_MIME_TYPES_PATH=/usr/share/mime/packages/freedesktop.org.xml

      - name: Sleep for 60 seconds
        run: sleep 1000

      - name: Run View Linter
        run: |
          git fetch --no-tags --depth=1 origin trunk
          bundle exec rake view_translations_linter:lint_git_difference_changed_lines
