name: full check suite
on:
  push:

concurrency:
  group: qb-${{ github.ref }}
  cancel-in-progress: true

env:
  REPORT_PATH: 'ci/cuke-report.json'
  CUCUMBER_SPLIT_CONFIGURATION_PATH: 'ci/cucumber-split-config.json'
  CLIENT: 'dc'

jobs:
  view_linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.3.26
      - name: Run View Linter
        run: |
          git fetch --no-tags --depth=1 origin trunk
          bundle exec rake view_translations_linter:lint_git_difference_changed_lines
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.3.26
      - run: gem install brakeman
      - run: brakeman -i config/brakeman.ignore
      - name: Run Brakeman In Components
        run: |
          for test_dir in `ls -1 components`; do
            cd components/$test_dir
            brakeman -i config/brakeman.ignore
            cd ../..
          done

  engines:
    runs-on: ubuntu-20.04
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --name "rabbitmq"
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongo:
        image: mongo:4.2
        ports:
          - 27017:27017
        options: >-
          --name "mongo"
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:3.2-alpine
        ports:
          - 6379
        options: >-
          --name "redis"
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        engine-name:
          [
            'benefit_markets',
            'notifier',
            'sponsored_benefits',
            'transport_gateway',
            'transport_profiles' 
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          rubygems: 3.3.26
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: restore Project Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: v5-${{ matrix.engine-name }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v5-${{ matrix.engine-name }}-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          gem update --system --quiet --silent
          bundle config path vendor/bundle
          bundle install
          echo switching to ${{ matrix.engine-name }}
          cd components/${{ matrix.engine-name }}
          bundle config path ../../vendor/bundle
          echo testing caching
          echo installing ${{ matrix.engine-name }} dependencies
          bundle install
      - name: Restore Node Modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
      - name: yarn install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: run webpack
        run: |
          echo bundle config
          bundle config path vendor/bundle
          NODE_ENV=test RAILS_ENV=test ./bin/webpack
      - name: test engine
        env:
          COVERAGE: 'true'
        run: |
          root=`pwd -P`
          echo $root/components/${{ matrix.engine-name }}
          cd $root/components/${{ matrix.engine-name }}
          bundle config path ../../vendor/bundle
          bundle exec rspec
      - name: copy coverage report
        run: |
          root=`pwd -P`
          cd $root/components/${{ matrix.engine-name }}
          cp coverage/coverage.xml ${{ github.workspace }}/engines-${{ matrix.group }}_${{ strategy.job-total }}_coverage.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ${{ github.workspace }}/engines-${{ matrix.group }}_${{ strategy.job-total }}_coverage.xml
  financial-assistance:
    runs-on: ubuntu-20.04
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --name "rabbitmq"
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongo:
        image: mongo:4.2
        ports:
          - 27017:27017
        options: >-
          --name "mongo"
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:3.2-alpine
        ports:
          - 6379
        options: >-
          --name "redis"
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        group: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.3.26
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Test Boosters gem
        run: gem install treye-semaphore_test_boosters --version '2.5.2'
      - name: Restore Node Modules
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-v14-${{ hashFiles('yarn.lock') }}
      - name: Install node dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Run tests
        env:
          COVERAGE: 'true'
          TEST_BOOSTERS_RSPEC_TEST_FILE_PATTERN: 'components/financial_assistance/**/*_spec.rb'
        run: rspec_booster --job ${{ matrix.group }}/${{ strategy.job-total }}
      - name: copy coverage report
        run: |
          cp coverage/coverage.xml ${{ github.workspace }}/coverage/fa_${{ matrix.group }}_${{ strategy.job-total }}_coverage.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ${{ github.workspace }}/coverage/fa_${{ matrix.group }}_${{ strategy.job-total }}_coverage.xml
