name: full check suite
on:
  push:

concurrency:
  group: qb-${{ github.ref }}
  cancel-in-progress: true

env:
  REPORT_PATH: 'ci/cuke-report.json'
  CUCUMBER_SPLIT_CONFIGURATION_PATH: 'ci/cucumber-split-config.json'
  CLIENT: 'dc'

jobs:
  view_linter:
    runs-on: ubuntu-runner
    steps:
      - uses: actions/checkout@v3
      - name: Install Git, Ruby, and dependencies
        run: |
          sudo apt update
          sudo apt install -y git ruby-full build-essential
      - name: Install libyaml-dev
        run: sudo apt install -y libyaml-dev
      - name: Create /opt/hostedtoolcache directory
        run: sudo mkdir -p /opt/hostedtoolcache
      - name: Give permission to runner user to read and write
        run: sudo chown runner /opt/hostedtoolcache && sudo chmod u+rw /opt/hostedtoolcache
#      - name: Use Bundler 2.3.24
#        run: gem install bundler -v 2.3.24
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.3.26
      - name: Install dependencies with Bundler
        run: bundle install --jobs 4 --retry 3
      - name: Run View Linter
        run: |
          git fetch --no-tags --depth=1 origin main
          bundle exec rake view_translations_linter:lint_git_difference_changed_lines
